"use client";

import { useEffect, useMemo, useState } from "react";

type Strand = "Number" | "Algebra" | "Measurement" | "Geometry" | "Statistics" | "Probability";
type YearLevel = 2 | 3 | 4 | 5;
type Topic = {
  id: string;
  strand: Strand;
  title: string;
  focus: string;
  summary: string;
  outcomes: string[];
  videoId: string;
  videoStart?: number;
  videoTitle: string;
  videoId2?: string;
  videoTitle2?: string;
  videoId3?: string;
  videoTitle3?: string;
  videoId4?: string;
  videoTitle4?: string;
  videoUrl?: string;
};
type Question = { prompt: string; choices: string[]; answer: string; hint: string };
type Progress = Record<string, { score: number; completedAt: string }>;
const PROGRESS_KEY="nz-maths-curriculum-progress";
const LEGACY_PROGRESS_KEY="ryan-year2-maths-progress";

const STRANDS: Strand[] = ["Number", "Algebra", "Measurement", "Geometry", "Statistics", "Probability"];
const CURRICULUM_URLS:Record<YearLevel,string> = {
  2:"https://www.education.govt.nz/parents-and-caregivers/schools-year-0-13/parent-portal/guide-for-the-new-zealand-curriculum-years-0-to-8/year-2-new-zealand-curriculum/mathematics-and-statistics-in-year-2",
  3:"https://www.education.govt.nz/parents-and-caregivers/schools-year-0-13/parent-portal/guide-for-the-new-zealand-curriculum-years-0-to-8/year-3-new-zealand-curriculum/mathematics-and-statistics-in-year-3",
  4:"https://www.education.govt.nz/parents-and-caregivers/schools-year-0-13/parent-portal/guide-for-the-new-zealand-curriculum-years-0-to-8/year-4-new-zealand-curriculum/mathematics-and-statistics-in-year-4",
  5:"https://www.education.govt.nz/parents-and-caregivers/schools-year-0-13/parent-portal/guide-for-the-new-zealand-curriculum-years-0-to-8/year-5-new-zealand-curriculum/mathematics-and-statistics-in-year-5",
};
const OFFICIAL_YEAR3_PRACTICE_URL="https://nzc-maths-practice.nz/year/Year%203/";
const COMPILATION = "RdzCXBgB-9s";
const NZ_COINS = [
  {value:"10c",alt:"Reverse of the New Zealand 10 cent coin",src:"/images/nz-money/10c-rbnz.png"},
  {value:"20c",alt:"Reverse of the New Zealand 20 cent coin",src:"/images/nz-money/20c-rbnz.png"},
  {value:"50c",alt:"Reverse of the New Zealand 50 cent coin",src:"/images/nz-money/50c-rbnz.png"},
  {value:"$1",alt:"Reverse of the New Zealand one dollar coin",src:"/images/nz-money/1-dollar-rbnz.png"},
  {value:"$2",alt:"Reverse of the New Zealand two dollar coin",src:"/images/nz-money/2-dollar-rbnz.png"},
];

const TOPICS: Topic[] = [
  { id:"numbers-120", strand:"Number", title:"Numbers to 120", focus:"Read • write • order", summary:"Read, write, order and describe whole numbers up to 120.", outcomes:["Recognise, read and write numbers to 120","Order numbers from smallest to largest","Say the number before and after"], videoId:"WwGwQ4oGloY", videoTitle:"Counting to 120 · Math & Learning Videos 4 Kids" },
  { id:"skip-counting", strand:"Number", title:"Counting & Skip Counting", focus:"Forward • backward • skip count", summary:"Count forwards and backwards in 1s, 2s, 5s and 10s from different starting points.", outcomes:["Count forwards and backwards","Skip count in 2s, 5s and 10s","Find missing numbers in a sequence"], videoId:"DhiklliLG80", videoTitle:"Skip Counting for Kids · Rock 'N Learn" },
  { id:"te-reo-numbers", strand:"Number", title:"Tau Māori to 100", focus:"Numbers in te reo Māori", summary:"Use te reo Māori for familiar numbers and build tens up to 100.", outcomes:["Recognise tahi to tekau","Build multiples of ten","Match English and te reo Māori numbers"], videoId:"Ik4mhRKQBds", videoTitle:"Tau Māori numbers · YouTube lesson" },
  { id:"place-value", strand:"Number", title:"Place Value", focus:"Hundreds • tens • ones", summary:"Show numbers as hundreds, tens and ones, then partition them in different ways.", outcomes:["Identify hundreds, tens and ones","Partition numbers such as 47 = 40 + 7","Explain the value of each digit"], videoId:"T5Qf0qSSJFI", videoTitle:"Place Value · Math Antics" },
  { id:"number-line", strand:"Number", title:"Number Lines & Comparing", focus:"Estimate • compare • odd and even", summary:"Locate approximate values on a number line and compare numbers using mathematical language.", outcomes:["Place values approximately on a 0–120 line","Use <, > and =","Identify odd and even numbers"], videoId:"tJrSILRXOUc", videoTitle:"Comparing Numbers on a Number Line · Khan Academy", videoId2:"3qisu9NF1_0", videoTitle2:"Greater Than, Less Than & Equal · NUMBEROCK", videoId3:"eF_FxSW8QwY", videoTitle3:"Even and Odd Numbers · Smile and Learn" },
  { id:"add-sub", strand:"Number", title:"Addition & Subtraction", focus:"Tens-and-ones strategies", summary:"Add and subtract by splitting numbers into tens and ones.", outcomes:["Add and subtract within 120","Use tens-and-ones strategies","Check whether an answer is reasonable"], videoId:"7J1OkxuyLD0", videoTitle:"Adding & Subtracting · Scratch Garden" },
  { id:"facts-doubles", strand:"Number", title:"Facts, Doubles & Halves", focus:"Facts within 20", summary:"Recall addition facts to 10 and explore related facts, doubles and halves to 20.", outcomes:["Recall addition facts to 10","Use related facts to 20","Find doubles and halves"], videoId:"lD9tjBUiXs0", videoTitle:"Number Bonds to 10 · Jack Hartmann", videoId2:"NDqbCfplYrg", videoTitle2:"Adding Doubles · Jack Hartmann", videoId3:"7EJHATyTek8", videoTitle3:"Teaching Halving Numbers · Maths with Mum" },
  { id:"groups-sharing", strand:"Number", title:"Equal Groups & Sharing", focus:"Groups of 2 • 5 • 10", summary:"Model multiplication and division using equal groups, sharing and skip counting.", outcomes:["Make equal groups of 2, 5 and 10","Connect repeated addition to multiplication","Share a set equally"], videoId:"fPDSp5HElZw", videoTitle:"Equal Groups · Improving Maths", videoId2:"fgoUVDoHx5M", videoTitle2:"How to Share Equally · Learningvids4kids" },
  { id:"fractions", strand:"Number", title:"Fractions", focus:"Halves • thirds • quarters", summary:"Recognise, show and compare halves, thirds and quarters of wholes and sets.", outcomes:["Recognise ½, ⅓ and ¼","Know that fractional parts must be equal","Find fractions of a set"], videoId:"362JVVvgYPE", videoTitle:"Fractions! · Scratch Garden" },
  { id:"money", strand:"Number", title:"New Zealand Money", focus:"Dollars • cents • totals to $20", summary:"Recognise New Zealand coins and notes, understand dollars and cents, and make and add money amounts up to $20.", outcomes:["Recognise NZ coin and note values","Know that 100 cents equals 1 dollar","Make and add money amounts up to $20"], videoId:"hbejMBy-PLg", videoTitle:"What Is Money? · ASB GetWise" },
  { id:"equations", strand:"Algebra", title:"True Equations & Missing Numbers", focus:"Equal means the same value", summary:"Understand equality, decide whether number sentences are true, and solve open equations.", outcomes:["Understand that = means both sides are equal","Use =, < and >","Find a missing number"], videoId:"gEGKvx1wlFg", videoTitle:"Equal sign · Khan Academy", videoId2:"jL-_SGVDP3Y", videoTitle2:"Comparing Numbers with <, > and = · Math & Learning Videos 4 Kids", videoId3:"hpNWjHDDZvM", videoTitle3:"True/False Equations and Missing Numbers · The Primary Math Teacher" },
  { id:"patterns", strand:"Algebra", title:"Repeating Patterns", focus:"Find • continue • explain", summary:"Identify the repeating unit, predict what comes next and find missing elements.", outcomes:["Identify what repeats","Continue three-element patterns","Describe a pattern rule"], videoId:"1WJcYwSu0-U", videoTitle:"Repeating Patterns · Kids Academy" },
  { id:"length", strand:"Measurement", title:"Length with Informal Units", focus:"Estimate • measure • compare", summary:"Estimate and measure length consistently using steps, string, pencils or paper clips.", outcomes:["Estimate before measuring","Measure with equal informal units","Compare longer, shorter, depth and width"], videoId:"q8MV4MY6rHs", videoTitle:"Measure Length with Nonstandard Units · The Eagle's Nest", videoId2:"Z-zITJHerSk", videoTitle2:"Compare Length with Nonstandard Units · The Eagle's Nest" },
{ id:"mass-capacity", strand:"Measurement", title:"Mass & Capacity", focus:"Heavier • lighter • holds more", summary:"Estimate and compare weight and capacity using blocks, cups and everyday containers.", outcomes:["Compare heavier and lighter","Compare shallow and deep","Measure capacity with equal cupfuls"], videoId:"E6iJI66AOv8", videoTitle:"Identifying Lighter and Heavier Using a Balance · The Eagle's Nest", videoId2:"5O8GxqU_lck", videoTitle2:"Measuring Capacity with Non-standard Units · TicTacLearn", videoId3:"znQFP8i3mPg", videoTitle3:"Understanding Capacity: More or Less · STEM School" },
  { id:"turns", strand:"Measurement", title:"Turns", focus:"Clockwise • anti-clockwise • fractions", summary:"Describe clockwise and anti-clockwise full, half, quarter and three-quarter turns.", outcomes:["Name common fractions of a turn","Distinguish clockwise and anti-clockwise","Predict a finishing direction"], videoId:"JxYjvrtGeBA", videoTitle:"Turns Part 1 · Matholia", videoId2:"3kxFbp6sLeA", videoTitle2:"Whole, Half, Quarter and Three-Quarter Turns · Insight HQ" },
  { id:"calendar", strand:"Measurement", title:"Calendar & Duration", focus:"Months • seasons • elapsed time", summary:"Order months and seasons, and describe spans using years, months, weeks, days and hours.", outcomes:["Name and order the months","Match NZ seasons to months","Choose sensible duration units"], videoId:"jr4HnhY4eUk", videoTitle:"Months, Days and Seasons · ClassMonitor", videoId2:"M4Wf9L6_PBA", videoTitle2:"Seasons in New Zealand: Temperature and Climate by Month · Alexey-L", videoId3:"061ePX3k-hA", videoTitle3:"Four Seasons in the Southern Hemisphere · Jack Hartmann", videoId4:"ULR9LWiaKRQ", videoTitle4:"Duration Units: Seconds, Minutes and Hours · Homeschool Pop" },
  { id:"clock", strand:"Measurement", title:"Analogue Time", focus:"O'clock • half past • quarter hours", summary:"Tell analogue time to the hour, half-hour and quarter-hour.", outcomes:["Read o'clock and half past","Read quarter past and quarter to","Match analogue language to digital time"], videoId:"d6FJx3va9bQ", videoTitle:"Telling Time: O'clock, Half Past and Quarters · Janine Williams", videoId2:"HKZOGR1pz1I", videoTitle2:"Telling Time: Quarter To · Learn and Play Online", videoId3:"X9wOtw8HGCI", videoTitle3:"Match Analogue Clocks to Digital Times · Little Dreamers Education" },
  { id:"shapes", strand:"Geometry", title:"2D & 3D Shapes", focus:"Name • describe • sort", summary:"Recognise, describe and sort shapes by edges, corners, faces and vertices.", outcomes:["Name common 2D and 3D shapes","Describe edges, faces and vertices","Sort shapes by their features"], videoId:"CYVmmTaqIPU", videoTitle:"Faces, Edges and Vertices · Noodle Kidz" },
  { id:"shape-moves", strand:"Geometry", title:"Slide & Turn Shape Patterns", focus:"Move • turn • continue", summary:"Slide and turn 2D shapes to create and continue patterns.", outcomes:["Recognise a slide","Recognise a turn","Predict the next shape orientation"], videoId:"X0hllwR2zL4", videoTitle:"Geometry Transformations: Flip, Slide and Turn · Math Song", videoId2:"nmCkZT_-9QY", videoTitle2:"Math Lesson: Slides, Flips and Turns", videoId3:"0Z1aUhGCZs0", videoTitle3:"Geometric Transformations · Colin Dodds" },
  { id:"position", strand:"Geometry", title:"Position & Directions", focus:"Position • movement • routes", summary:"Follow and give movement instructions, including distances and turns, and read simple diagrams.", outcomes:["Use left, right, forward and backward","Follow multi-step directions","Describe an object's position"], videoId:COMPILATION, videoStart:3344, videoTitle:"Location & Directions · Scratch Garden" },
  { id:"collect-data", strand:"Statistics", title:"Collect & Represent Data", focus:"Tallies • tables • graphs", summary:"Sort and record data using tallies, tables, picture graphs and dot plots.", outcomes:["Choose a useful survey question","Record tally marks in groups of five","Read tables, picture graphs and dot plots"], videoId:COMPILATION, videoStart:3804, videoTitle:"Data · Scratch Garden", videoId2:"Va_slzMjcgg", videoTitle2:"Tally Charts: Groups of Five · IXL", videoId3:"yZJR2MzkBrU", videoTitle3:"Picture Graphs · NUMBEROCK", videoId4:"BOOcZfnTYPo", videoTitle4:"Dot Plots · Elementary Math" },
  { id:"interpret-data", strand:"Statistics", title:"Compare & Explain Data", focus:"Most • least • more • total • conclude", summary:"Read graphs and tables to compare categories, calculate differences and totals, and choose conclusions supported by the data.", outcomes:["Find most and least common categories","Answer how many more and total questions","Choose a conclusion supported by data"], videoId:"twz45pt3Cp4", videoTitle:"Compare Picture and Bar Graphs · Khan Academy", videoId2:"Va_slzMjcgg", videoTitle2:"Most, Least, How Many More and Total · IXL" },
];

const YEAR3_TOPICS:Topic[] = [
  {id:"y3-numbers-1000",strand:"Number",title:"Numbers & Place Value to 1,000",focus:"Read • write • compare • order",summary:"Read, write, compare and order whole numbers to 1,000, and explain the value of every digit.",outcomes:["Read and write numbers to 1,000","Compare and order three-digit numbers","Partition hundreds, tens and ones"],videoId:"kVHFnVXBeSU",videoTitle:"Read & Write Numbers to 1,000 · MightyOwl",videoId2:"bg3FTgTmfkE",videoTitle2:"Compare & Order Three-Digit Numbers · Miacademy"},
  {id:"y3-facts",strand:"Number",title:"Multiplication & Division Facts",focus:"2s • 3s • 4s • 5s • 8s • 10s",summary:"Count forwards and backwards and recall multiplication and division facts for the Year 3 fact families.",outcomes:["Skip count in 2s, 3s, 4s, 5s, 8s and 10s","Recall multiplication facts","Use related division facts"],videoId:"_D6IPnvX0dY",videoTitle:"Skip Counting by Fact Families · Homeschool Pop",videoId2:"oPINS56lDes",videoTitle2:"Times Tables 1–12 · Numberock",videoId3:"YDXNJdvsAP0",videoTitle3:"Division as Grouping & Sharing · Math with Mr. J"},
  {id:"y3-groups",strand:"Number",title:"Multiplying, Grouping & Sharing",focus:"Use facts to solve problems",summary:"Use known facts to solve multiplication and division problems, including equal grouping and sharing.",outcomes:["Solve problems such as 2 × 23","Solve division such as 24 ÷ 3","Model equal groups and equal sharing"],videoId:"gzFbUZ8VjEg",videoTitle:"Equal Groups & Repeated Addition · Numberock",videoId2:"YDXNJdvsAP0",videoTitle2:"Division as Grouping & Sharing · Math with Mr. J",videoId3:"fgoUVDoHx5M",videoTitle3:"Share Equally · Learningvids4kids"},
  {id:"y3-add-sub",strand:"Number",title:"Addition & Subtraction to 1,000",focus:"Single-step • multi-step",summary:"Solve single-step and multi-step addition and subtraction problems with totals up to 1,000.",outcomes:["Add within 1,000","Subtract within 1,000","Solve two-step number problems"],videoId:"IW8qg7eZOTo",videoTitle:"Two-Step Addition & Subtraction Problems · Khan Academy",videoId2:"6glibvaWomw",videoTitle2:"Addition & Subtraction Word Problems to 1,000 · MightyOwl"},
  {id:"y3-rounding",strand:"Number",title:"Rounding & Estimation",focus:"Predict • calculate • check",summary:"Round numbers and estimate to predict and check whether calculated answers are reasonable.",outcomes:["Round to the nearest 10","Round to the nearest 100","Use estimates to check answers"],videoId:"pNfz-JU2cKE",videoTitle:"Rounding Numbers to Tens & Hundreds · NUMBEROCK"},
  {id:"y3-fraction-represent",strand:"Number",title:"Represent Fractions",focus:"Groups • number lines • counting",summary:"Read, write and represent fractions of groups and on number lines, then count in fractions up to one whole.",outcomes:["Write fractions of groups","Place fractions on a number line","Count in fractions with one denominator"],videoId:"SZaXtOHNh6s",videoTitle:"Fractions of Groups · NUMBEROCK",videoId2:"suDeJ8TDPw4",videoTitle2:"Counting Fractions on a Number Line · Teacher Math Lesson"},
  {id:"y3-fraction-compare",strand:"Number",title:"Compare Unit Fractions",focus:"Denominators up to 12",summary:"Compare unit fractions with denominators up to 12 and explain which fraction is greater.",outcomes:["Recognise unit fractions","Compare denominators up to 12","Use <, > and = with fractions"],videoId:"Tuzn9WOoKQg",videoTitle:"Comparing Fractions for Kids · Math with Mr. J",videoId2:"f7hdblvyZNw",videoTitle2:"Comparing Fractions with < and > · NUMBEROCK"},
  {id:"y3-fraction-add",strand:"Number",title:"Add & Subtract Fractions",focus:"Same denominator • within one whole",summary:"Add and subtract fractions that have the same denominator without going beyond one whole.",outcomes:["Add fractions with the same denominator","Subtract fractions with the same denominator","Keep the denominator unchanged"],videoId:"XIQCanP74qw",videoTitle:"Add & Subtract Like Denominators · Math with Mr. J"},
  {id:"y3-money",strand:"Number",title:"New Zealand Money & Change",focus:"Dollars • cents • change",summary:"Represent dollars and cents without decimal notation, add prices and calculate change in New Zealand money.",outcomes:["Write amounts as dollars and cents","Add New Zealand money amounts","Calculate change from a payment"],videoId:"hbejMBy-PLg",videoTitle:"What Is Money? · ASB Bank",videoId2:"zBR72_XijB0",videoTitle2:"New Zealand Coins & Currency · Reserve Bank of New Zealand"},
  {id:"y3-equality",strand:"Algebra",title:"Equality & Missing Numbers",focus:"Unknowns • true or false",summary:"Use the equals sign correctly, find missing numbers and decide whether equations are true or false.",outcomes:["Find an unknown value","Understand both sides must be equal","Test whether an equation is true"],videoId:"gEGKvx1wlFg",videoTitle:"The Equal Sign Means the Same · Math with Mr. J",videoId2:"hpNWjHDDZvM",videoTitle2:"True or False Equations & Missing Numbers · Math with Mr. J"},
  {id:"y3-repeat-pattern",strand:"Algebra",title:"Repeating Patterns",focus:"Identify • create • continue",summary:"Identify, create and continue repeating patterns using objects, colours, sounds and symbols.",outcomes:["Find the repeating unit","Continue a repeating pattern","Create a repeating pattern"],videoId:"pm1rUg61zX8",videoTitle:"Repeating Patterns for Kids · Math with Mr. J"},
  {id:"y3-growing-pattern",strand:"Algebra",title:"Growing Patterns",focus:"Numbers • shapes • change",summary:"Identify, create and continue patterns that grow by a consistent amount or action.",outcomes:["Recognise how a pattern grows","Continue number and shape patterns","Find missing pattern elements"],videoId:"2_VHHCUCYqs",videoTitle:"Growing Patterns for Kids · Learning with Santino"},
  {id:"y3-pattern-rules",strand:"Algebra",title:"Pattern Rules",focus:"Describe • apply • explain",summary:"Describe pattern rules such as alternating colours or adding the same amount each time.",outcomes:["State a pattern rule","Use a rule to find later terms","Match a pattern to its rule"],videoId:"PLAUecpfNLU",videoTitle:"Find the Pattern Rule · Math Quiz for Kids"},
  {id:"y3-metric",strand:"Measurement",title:"Metric Measurement",focus:"cm • m • g • kg • ml • l",summary:"Estimate and measure length, mass and capacity with metric units and suitable tools.",outcomes:["Choose a suitable metric unit","Use rulers, jugs and scales","Estimate before measuring"],videoId:"ZNX-a-5jGeM",videoTitle:"Metric Units of Measurement · Math Antics",videoId2:"XOvxggo3Re8",videoTitle2:"Millilitres & Litres: Capacity · FuseSchool"},
  {id:"y3-compare-measure",strand:"Measurement",title:"Compare Size & Weight",focus:"Compare • order • explain",summary:"Compare and order objects according to measurable size, length, capacity and weight.",outcomes:["Compare measurements in the same unit","Order objects by size or weight","Use heavier, lighter, longer and shorter"],videoId:"iz7Ux7kq1Ho",videoTitle:"Compare Lengths by Measuring · Kids Academy",videoId2:"E6iJI66AOv8",videoTitle2:"Heavier and Lighter · Happy Learning English",videoId3:"znQFP8i3mPg",videoTitle3:"Compare Capacity: More and Less · Happy Learning English"},
  {id:"y3-perimeter",strand:"Measurement",title:"Perimeter",focus:"Measure around a boundary",summary:"Find the perimeter of a shape by walking or measuring all the way around its boundary.",outcomes:["Identify the boundary","Add side lengths","Find the perimeter of rectangles"],videoId:"MTSlKifo4js",videoTitle:"Perimeter for Kids · Homeschool Pop"},
  {id:"y3-area",strand:"Measurement",title:"Area with Squares",focus:"Cover • count • square units",summary:"Measure the area of simple shapes by covering and counting equal-sized squares.",outcomes:["Understand area covers a surface","Count square units","Find the area of simple rectangles"],videoId:"8cz_IB65pZM",videoTitle:"Area for Kids · Homeschool Pop"},
  {id:"y3-event-duration",strand:"Measurement",title:"Duration of Events",focus:"Years to seconds",summary:"Identify how long events last using years, months, weeks, days, hours, minutes and seconds.",outcomes:["Choose a sensible duration unit","Estimate how long events last","Order events by duration"],videoId:"YppG6YY9JPs",videoTitle:"Units of Time for Kids · Homeschool Pop",videoId2:"mTMq7w7DVOU",videoTitle2:"Seconds, Minutes, Hours, Days, Weeks, Months & Years · Happy Learning English"},
  {id:"y3-clock",strand:"Measurement",title:"Analogue & Digital Time",focus:"Nearest 5 minutes • nearest minute",summary:"Tell analogue and digital time using minutes past and minutes to the hour.",outcomes:["Read times to the nearest 5 minutes","Read times to the nearest minute","Use minutes past and minutes to"],videoId:"o4gKu1brlWA",videoTitle:"Tell Time to the Nearest Minute · Math with Mr. J",videoId2:"v7VvIVN-BSc",videoTitle2:"Minutes Past and Minutes To · Homeschool Pop",videoId3:"Pxr0dySHsgU",videoTitle3:"Telling Time to the Nearest 5 Minutes · eSpark"},
  {id:"y3-time-units",strand:"Measurement",title:"Compare Units of Time",focus:"Convert • compare • explain",summary:"Describe relationships between units of time and compare durations from seconds to years.",outcomes:["Know key time-unit relationships","Compare durations in different units","Explain why a unit is suitable"],videoId:"YppG6YY9JPs",videoTitle:"Units of Time for Kids · Homeschool Pop",videoId2:"mTMq7w7DVOU",videoTitle2:"Seconds, Minutes, Hours, Days, Weeks, Months & Years · Happy Learning English"},
  {id:"y3-polygons",strand:"Geometry",title:"Regular Shapes to 10 Sides",focus:"Triangles to decagons",summary:"Find and describe regular two-dimensional shapes with up to 10 sides.",outcomes:["Name polygons with 3 to 10 sides","Count sides and corners","Recognise regular shapes"],videoId:"DUGkQMLowXA",videoTitle:"Polygons for Kids · Smile and Learn",videoId2:"UN57vvrMrY4",videoTitle2:"Regular and Irregular Polygons · Math with Mr. J"},
  {id:"y3-sort-shapes",strand:"Geometry",title:"Sort Shapes by Features",focus:"Sides • corners • faces",summary:"Compare and sort 2D and 3D shapes according to their mathematical features.",outcomes:["Sort by number of sides or corners","Describe faces, edges and vertices","Explain a sorting rule"],videoId:"ClznfayCVW0",videoTitle:"Sort 2D and 3D Shapes · Math with Mr. J",videoId2:"CYVmmTaqIPU",videoTitle2:"Faces, Edges and Vertices · Noodle Kidz"},
  {id:"y3-symmetry",strand:"Geometry",title:"Lines of Symmetry",focus:"Reflect • complete • create",summary:"Recognise lines of symmetry and complete or create symmetrical pictures and patterns.",outcomes:["Identify symmetrical designs","Find a line of symmetry","Complete a reflected pattern"],videoId:"1u57rNNxDHg",videoTitle:"Lines of Symmetry for Kids · Homeschool Pop",videoId2:"KVem0i8qOek",videoTitle2:"Lines of Symmetry · Math with Mr. J"},
  {id:"y3-directions",strand:"Geometry",title:"Movement & Turns",focus:"Steps • distance • quarter and half turns",summary:"Follow and give step-by-step movement instructions using distance and quarter or half turns.",outcomes:["Follow ordered directions","Use half and quarter turns","Include how far to move"],videoId:"G9W2kTa_BH0",videoTitle:"Directions, Clockwise & Anti-clockwise Turns · Twinkl",videoId2:"HnlJzWhsNnw",videoTitle2:"Giving Directions and Distance · Scratch Garden"},
  {id:"y3-maps",strand:"Geometry",title:"Simple Maps & Location",focus:"North • south • east • west",summary:"Use simple maps and positional language to describe where places are in relation to one another.",outcomes:["Read a simple grid map","Use compass directions","Describe relative location"],videoId:"xR0Tq8Rkg6c",videoTitle:"Simple Grid Maps for Kids · Twinkl",videoId2:"ibLedhew2r0",videoTitle2:"Cardinal Directions for Kids · Homeschool Pop"},
  {id:"y3-data-collect",strand:"Statistics",title:"Ask, Collect & Organise Data",focus:"Questions • surveys • categories",summary:"Ask statistical questions, collect information and organise responses into useful categories.",outcomes:["Ask a question with varied answers","Collect survey responses","Organise data into categories"],videoId:"ONADbRedHxE",videoTitle:"Collecting Data with a Survey · Math for Kids",videoId2:"zF_dBk8EPDk",videoTitle2:"Collect, Organise and Graph Data · Scratch Garden"},
  {id:"y3-data-present",strand:"Statistics",title:"Present Data",focus:"Tallies • tables • picture, dot and bar graphs",summary:"Present collected information using tallies, tables, picture graphs, dot plots and bar graphs.",outcomes:["Choose a suitable display","Read graph scales and labels","Represent data accurately"],videoId:"x0Pn3mJUzZE",videoTitle:"Making Tally Charts · Math for Kids",videoId2:"yZJR2MzkBrU",videoTitle2:"Bar Graphs & Picture Graphs · NUMBEROCK",videoId3:"BOOcZfnTYPo",videoTitle3:"Dot Plots for Kids · Math with Mr. J"},
  {id:"y3-data-answer",strand:"Statistics",title:"Answer Questions with Data",focus:"Compare • total • conclude",summary:"Answer questions about collected data and describe what the information shows.",outcomes:["Find common and uncommon results","Compare categories","Make a conclusion supported by data"],videoId:"Va_slzMjcgg",videoTitle:"Counting, Comparing and Finding Totals · IXL",videoId2:"twz45pt3Cp4",videoTitle2:"Compare Picture and Bar Graphs · Khan Academy",videoId3:"ChNSv1Agcbk",videoTitle3:"Draw Conclusions from Data · Math with Mr. J"},
];

const YEAR4_TOPICS:Topic[] = [
  {id:"y4-numbers-10000",strand:"Number",title:"Numbers & Operations to 10,000",focus:"Read • order • add • subtract",summary:"Read, write, compare and order numbers to 10,000, then add and subtract 2-, 3- and 4-digit numbers.",outcomes:["Read, write, order and compare to 10,000","Add and subtract 2-, 3- and 4-digit numbers","Use place value to explain a method"],videoId:"XhNHrtipltM",videoTitle:"Numbers to 10,000 and Place Value · Reaby Learning Lab",videoId2:"GVSMC1ccVhI",videoTitle2:"4-Digit Addition · Math with Mr. J",videoId3:"HlxqCdDrbdc",videoTitle3:"Subtracting Large Numbers · Math with Mr. J"},
  {id:"y4-round-decimals",strand:"Number",title:"Rounding & Decimal Tenths",focus:"Estimate • tenths • one decimal place",summary:"Use rounding to estimate and check answers, and connect tenths written as fractions and decimals.",outcomes:["Round to the nearest 10, 100 and 1,000","Connect tenths and decimal notation","Add and subtract one-decimal-place numbers"],videoId:"KkswD4iPyO0",videoTitle:"Step-by-Step Whole Number Rounding · Math with Mr. J",videoId2:"asOD7H6C8ig",videoTitle2:"Decimal Models: Tenths · Math with Mr. J",videoId3:"PnwLv6khwk8",videoTitle3:"Add and Subtract Decimals · Math with Mr. J"},
  {id:"y4-times-facts",strand:"Number",title:"Times Tables & Fact Families",focus:"2–10 times tables • inverse facts",summary:"Recall the 2 to 10 times tables and use multiplication and division fact families to solve problems.",outcomes:["Recall the 2 to 10 times tables","Use multiplication and related division facts","Solve multiplication and division problems"],videoId:"",videoTitle:"2–10 Times Table Reference",videoId2:"RPNm23iu4R4",videoTitle2:"Related Multiplication and Division Facts · MATH-N-ROLL"},
  {id:"y4-multiply-divide",strand:"Number",title:"Multiply & Divide Larger Numbers",focus:"23 × 5 • 44 ÷ 4 • remainders",summary:"Multiply and divide using known facts, arrays, place value and inverse operations.",outcomes:["Solve multiplication such as 23 × 5","Solve division such as 44 ÷ 4","Use a family of facts to check"],videoId:"od-tHGrudcA",videoTitle:"3-Digit by 1-Digit Multiplication · Math with Mr. J",videoId2:"oeinRbaqxLk",videoTitle2:"2-Digit by 1-Digit Division · Maths with Mrs B"},
  {id:"y4-fractions-wholes",strand:"Number",title:"Fractions of Amounts & Wholes",focus:"Equivalent • fraction of a set • find the whole",summary:"Find fractions of amounts, find the whole when a fractional part is known, and use equivalent fractions.",outcomes:["Find a fraction of a whole amount","Find the whole from a fractional part","Recognise equivalent fractions"],videoId:"ZF5Viuwo1bw",videoTitle:"Finding Fractions of Whole Numbers · Math with Mr. J",videoId2:"BcE6yOM4YaM",videoTitle2:"Find the Whole from a Known Fraction · Mr McLean Math",videoId3:"dBZ2QGZBH6M",videoTitle3:"Equivalent Fractions · Math with Mr. J"},
  {id:"y4-fraction-calculate",strand:"Number",title:"Add & Subtract Fractions",focus:"Same denominator • mixed numbers",summary:"Add and subtract fractions with a common denominator, including answers greater than one whole.",outcomes:["Add fractions with the same denominator","Subtract fractions with the same denominator","Rename an improper fraction as a mixed number"],videoId:"XIQCanP74qw",videoTitle:"Add and Subtract Like Denominators · Math with Mr. J",videoId2:"EpXCr2iax5E",videoTitle2:"Improper Fractions to Mixed Numbers · Math with Mr. J"},
  {id:"y4-nz-money",strand:"Number",title:"New Zealand Money & Rounding",focus:"Dollars • cents • change • nearest dollar",summary:"Make and calculate money amounts in New Zealand dollars and cents, calculate change and round money to the nearest dollar.",outcomes:["Make amounts using dollars and cents","Calculate totals and change","Round money to the nearest dollar"],videoId:"hbejMBy-PLg",videoTitle:"What Is Money? · ASB Bank",videoId2:"Z2ejhmKHY3k",videoTitle2:"Making Change by Counting Up · MooMooMath and Science",videoId3:"sD6NNfdHtS0",videoTitle3:"Adding Money Amounts · Let’s Do Math",videoId4:"VGqoitu8HdE",videoTitle4:"Round to the Nearest Dollar · Math with Mr. J"},
  {id:"y4-equations-patterns",strand:"Algebra",title:"Equations & Growing Patterns",focus:"True or false • missing number • growth rule",summary:"Check equations, use missing numbers and describe growing patterns made by adding, subtracting or multiplying.",outcomes:["Check whether number sentences are true or false","Find missing values using all four operations","Continue and explain a growing pattern"],videoId:"L0_K89UJfJY",videoTitle:"One-Step Equations: All Four Operations · Math with Mr. J",videoId2:"_u-SBkNU5YM",videoTitle2:"Patterns and Relationships · Math with Mr. J"},
  {id:"y4-metric-temperature",strand:"Measurement",title:"Metric Units & Temperature",focus:"m • cm • kg • g • l • °C",summary:"Estimate and measure with appropriate metric units and measure temperature in degrees Celsius.",outcomes:["Choose metres, centimetres, kilograms, grams and litres","Estimate then measure accurately","Read temperature in degrees Celsius"],videoId:"ZNX-a-5jGeM",videoTitle:"Metric Units of Measurement · Math Antics",videoId2:"XOvxggo3Re8",videoTitle2:"Millilitres & Litres: Capacity · FuseSchool",videoId3:"ZXTx4jAKEvA",videoTitle3:"How to Read a Thermometer · Miacademy"},
  {id:"y4-area-perimeter-volume",strand:"Measurement",title:"Perimeter, Area & Volume",focus:"Boundary • squares • cubes",summary:"Measure perimeter, find area with squares and explore volume using layers of cubes.",outcomes:["Find perimeter by measuring around a boundary","Find area using squares","Build volume with cubes"],videoId:"2UEUWC313QY",videoTitle:"Perimeter, Area and Volume · Math with Mr. J",videoId2:"8cz_IB65pZM",videoTitle2:"Area for Kids · Homeschool Pop",videoId3:"By7sVb2IhFs",videoTitle3:"Volume of Rectangular Prisms · Math with Mr. J"},
  {id:"y4-angles-time",strand:"Measurement",title:"Angles, Turns & Time",focus:"90° • 180° • 360° • minutes",summary:"Compare angles to benchmark turns and read an analogue clock to the nearest minute using past and to language.",outcomes:["Recognise right, straight and full turns","Estimate angles using 90°, 180° and 360°","Read time to the nearest minute using past and to"],videoId:"6QfnD0WRimQ",videoTitle:"Turns and Right Angles: 90°, 180° and 360° · Math with Shazia",videoId2:"o4gKu1brlWA",videoTitle2:"Tell Time to the Nearest Minute · Math with Mr. J",videoId3:"v7VvIVN-BSc",videoTitle3:"Minutes Past and Minutes To · Homeschool Pop"},
  {id:"y4-duration",strand:"Measurement",title:"Equivalent Durations",focus:"Seconds to years • convert time",summary:"Use relationships between time units to find equivalent durations such as three weeks equal 21 days.",outcomes:["Know key time-unit relationships","Find equivalent durations","Choose sensible time units"],videoId:"YppG6YY9JPs",videoTitle:"Units of Time for Kids · Homeschool Pop",videoId2:"mTMq7w7DVOU",videoTitle2:"Seconds, Minutes, Hours, Days, Weeks, Months & Years · Happy Learning English"},
  {id:"y4-polygons-symmetry",strand:"Geometry",title:"Polygons & Symmetry",focus:"Up to 12 sides • angles • reflections",summary:"Describe polygons using sides and angles and identify lines of symmetry in two-dimensional shapes.",outcomes:["Name and describe shapes up to 12 sides","Use sides and angles to describe polygons","Find lines of symmetry"],videoId:"DUGkQMLowXA",videoTitle:"Polygons for Kids · Smile and Learn",videoId2:"ae_ZBJuqDlI",videoTitle2:"Parts of a Polygon: Sides, Angles and Vertices · Math with Mr. J",videoId3:"1u57rNNxDHg",videoTitle3:"Lines of Symmetry for Kids · Homeschool Pop"},
  {id:"y4-transformations",strand:"Geometry",title:"Transformations & 3D Views",focus:"Reflect • rotate • translate • perspective",summary:"Flip, turn and slide 2D shapes, and visualise three-dimensional objects from different viewpoints.",outcomes:["Reflect, rotate and translate 2D shapes","Describe how a shape changes","Visualise a 3D object from different perspectives"],videoId:"YD3HIMUae_4",videoTitle:"Transformations: Reflection, Rotation and Translation · Math Defined",videoId2:"xVaZ85XIupk",videoTitle2:"Perspective of 3D Shapes · Periwinkle"},
  {id:"y4-grid-maps",strand:"Geometry",title:"Grid Maps & Directions",focus:"Letters • numbers • routes",summary:"Read maps and give directions using grid references, letters and numbers.",outcomes:["Read a grid map","Locate places using a letter and number","Give a route using directions"],videoId:"xR0Tq8Rkg6c",videoTitle:"Simple Grid Maps for Kids · Twinkl",videoId2:"HnlJzWhsNnw",videoTitle2:"Giving Directions and Distance · Scratch Garden"},
  {id:"y4-variables-graphs",strand:"Statistics",title:"Variables & Graphs",focus:"Categories • counts • labels • scale",summary:"Classify variables and create clear data displays with a title, labels, values and a scale starting at zero.",outcomes:["Recognise categorical, counted and measured variables","Create a graph with title, labels and units","Use a scale that starts at zero"],videoId:"DUcXZ08IdMo",videoTitle:"Categorical and Numerical Data · 365 Data Science",videoId2:"YIb-JyLLxwQ",videoTitle2:"Bar Graphs for Grade 4 and 5 · Tutway",videoId3:"-D1ZVJn08K0",videoTitle3:"How to Choose a Graph Scale · Mr Doey"},
  {id:"y4-dot-bar-graphs",strand:"Statistics",title:"Dot Plots, Bar Graphs & Trends",focus:"Display • compare • interpret",summary:"Show numerical data with dot plots or bar graphs and interpret patterns, trends and differences.",outcomes:["Choose a dot plot or bar graph for number data","Read patterns and differences","Interpret what the graph shows"],videoId:"qg8PMqJV3t0",videoTitle:"How to Make a Dot Plot · Math with Mr. J",videoId2:"twz45pt3Cp4",videoTitle2:"Understanding Picture and Bar Graphs · Khan Academy"},
];

const YEAR5_TOPICS:Topic[] = [
  {id:"y5-numbers-million",strand:"Number",title:"Numbers to One Million",focus:"Read • compare • order • negative",summary:"Read, write, compare, order and calculate with numbers to one million, including negative whole numbers.",outcomes:["Read, write and order numbers to one million","Round large whole numbers","Count backwards through zero into negative numbers"],videoId:"lDXUtDhgFc0",videoTitle:"Place Value to One Million · Maths with Mrs B",videoId2:"pNfz-JU2cKE",videoTitle2:"Rounding Numbers · NUMBEROCK",videoId3:"_uU5j2sMC84",videoTitle3:"Negative Numbers for Kids · Math with Mr. J"},
  {id:"y5-multiply-divide",strand:"Number",title:"Multiply, Divide & Remainders",focus:"3–4 digits • 2-digit × 2-digit • remainder",summary:"Multiply larger whole numbers and divide up to four digits by one digit, including remainders.",outcomes:["Recall the 11 and 12 times tables","Multiply 3- and 4-digit numbers by one digit","Multiply two 2-digit numbers","Divide with a remainder"],videoId:"od-tHGrudcA",videoTitle:"3-Digit by 1-Digit Multiplication · Math with Mr. J",videoId2:"up_xKZ6GeUg",videoTitle2:"Long Division with Remainders · Math with Mr. J",videoId3:"PZjIT9CH6bM",videoTitle3:"2-Digit by 2-Digit Multiplication · Math with Mr. J",videoId4:"oPINS56lDes",videoTitle4:"11 and 12 Times Tables · Numberock"},
  {id:"y5-decimals",strand:"Number",title:"Decimals to Hundredths",focus:"Compare • add • subtract",summary:"Read, write, compare, add and subtract numbers with two decimal places using place value and formal methods.",outcomes:["Read and compare hundredths","Add and subtract decimals to two places","Use place value and column methods"],videoId:"YWzVA5h94T0",videoTitle:"Ordering Decimals to Hundredths · Math with Mr. J",videoId2:"PnwLv6khwk8",videoTitle2:"Add and Subtract Decimals · Math with Mr. J"},
  {id:"y5-fractions-percentages",strand:"Number",title:"Fractions, Decimals & Percentages",focus:"½ • ¼ • ¾ • 10% • 25% • 50%",summary:"Connect common fractions, decimals and percentages and find fractions or percentages of a whole amount.",outcomes:["Match common fractions, decimals and percentages","Find simple fractions and percentages of amounts","Find the whole when one fractional part is known"],videoId:"tZMj0OX5WJ8",videoTitle:"Converting Fractions to Percents · Math with Mr. J",videoId2:"G3LZb71D3eA",videoTitle2:"Finding Fractions of Amounts · Math with Mr. J"},
  {id:"y5-fraction-calculate",strand:"Number",title:"Compare & Calculate Fractions",focus:"Related denominators • equivalent values",summary:"Add, subtract and compare fractions when one denominator is a multiple of the other.",outcomes:["Find equivalent fractions","Compare fractions with related denominators","Add and subtract related denominators"],videoId:"z7fZq3QGb6Q",videoTitle:"Equivalent Fractions · Math with Mr. J",videoId2:"Tuzn9WOoKQg",videoTitle2:"Comparing Fractions · Math with Mr. J",videoId3:"oI9KkTvqkes",videoTitle3:"Add and Subtract Fractions · Math with Mr. J"},
  {id:"y5-nz-money",strand:"Number",title:"New Zealand Money in Decimals",focus:"Notes • coins • totals • change",summary:"Represent New Zealand money with decimal notation, calculate totals and change, and round to the nearest ten dollars.",outcomes:["Write money in decimal notation","Calculate total cost and change","Round money to the nearest ten dollars"],videoId:"hbejMBy-PLg",videoTitle:"What Is Money? · ASB Bank",videoId2:"zBR72_XijB0",videoTitle2:"New Zealand Coins & Currency · Reserve Bank of New Zealand",videoId3:"pNfz-JU2cKE",videoTitle3:"Rounding Numbers · NUMBEROCK"},
  {id:"y5-equations-patterns",strand:"Algebra",title:"Inequalities, Equations & Patterns",focus:"< • > • = • missing values • rules",summary:"Use comparison symbols, solve missing-value equations and describe growing number patterns.",outcomes:["Use <, > and = on a number line","Complete equations with all four operations","Describe and extend growing patterns"],videoId:"jL-_SGVDP3Y",videoTitle:"Greater Than, Less Than and Equal · Math & Learning Videos 4 Kids",videoId2:"hpNWjHDDZvM",videoTitle2:"True/False Equations and Missing Numbers · Math with Mr. J",videoId3:"2_VHHCUCYqs",videoTitle3:"Growing Patterns for Kids · Learning with Santino"},
  {id:"y5-measurement-tools",strand:"Measurement",title:"Measuring with Accurate Tools",focus:"Ruler • scales • jugs • thermometer • protractor • timer",summary:"Select and use accurate measuring tools and units for everyday length, mass, capacity, temperature, angle and time.",outcomes:["Choose the correct tool and unit","Measure accurately with metric tools","Record compound time such as 2 hours 30 minutes"],videoId:"ZNX-a-5jGeM",videoTitle:"Metric Units of Measurement · Math Antics",videoId2:"gR-9xQHjPl8",videoTitle2:"Reading a Thermometer in Celsius · Math with Mr. J",videoId3:"Yb3a8p2hXcE",videoTitle3:"Measuring Angles with a Protractor · Math with Mr. J"},
  {id:"y5-area-volume-perimeter",strand:"Measurement",title:"Area, Volume & Perimeter",focus:"Rectangles • cubes • compare",summary:"Calculate rectangular area, volume by layers and perimeter, then compare shapes with equal area or equal perimeter.",outcomes:["Find rectangle area using length × width","Find volume using layers of cubes","Explain equal area and equal perimeter can differ"],videoId:"rBpsauKXPfs",videoTitle:"Area and Perimeter of Composite Shapes · Math with Mr. J",videoId2:"By7sVb2IhFs",videoTitle2:"Volume of Rectangular Prisms · Math with Mr. J",videoId3:"2UEUWC313QY",videoTitle3:"Perimeter, Area and Volume · Math with Mr. J"},
  {id:"y5-irregular-area",strand:"Measurement",title:"Irregular Area & Angles",focus:"Full squares • half squares • protractor",summary:"Estimate irregular area by counting squares and use a protractor to measure and draw angles up to 180 degrees.",outcomes:["Estimate area using full and partial squares","Measure angles with a protractor","Name acute, right, obtuse and straight angles"],videoId:"B4qFZ-f5c2c",videoTitle:"Area of Irregular Shapes · Math with Mr. J",videoId2:"Yb3a8p2hXcE",videoTitle2:"Measuring Angles with a Protractor · Math with Mr. J"},
  {id:"y5-timetables",strand:"Measurement",title:"Timetables, AM/PM & 24-Hour Time",focus:"Analogue • digital • duration",summary:"Read analogue and digital times and calculate elapsed time using am, pm and 24-hour notation.",outcomes:["Read analogue and digital time","Use am, pm and 24-hour time","Calculate elapsed duration"],videoId:"svPu5qGc8SM",videoTitle:"12- and 24-Hour Time · Maths",videoId2:"iuF5Fm5GmFA",videoTitle2:"Elapsed Time on Number Lines · Math with Mr. J"},
  {id:"y5-prisms-nets",strand:"Geometry",title:"Prisms, Cross-Sections & Nets",focus:"Faces • edges • cross-sections • nets",summary:"Explore prisms, their faces and edges, cross-sections and nets.",outcomes:["Describe prisms using faces, edges and corners","Recognise cross-sections","Match a 3D shape to its net"],videoId:"CYVmmTaqIPU",videoTitle:"Faces, Edges and Vertices · Noodle Kidz",videoId2:"Aq7I95SWK5s",videoTitle2:"Nets of 3D Shapes · Math with Mr. J"},
  {id:"y5-parallel-perpendicular",strand:"Geometry",title:"Parallel, Perpendicular & Transformations",focus:"Lines • reflect • rotate • translate",summary:"Identify parallel and perpendicular lines and describe reflections, rotations and translations of shapes.",outcomes:["Identify parallel lines","Identify perpendicular lines","Describe reflection, rotation and translation"],videoId:"ZP2w2uMneN0",videoTitle:"Parallel and Perpendicular Lines · Math with Mr. J",videoId2:"X0hllwR2zL4",videoTitle2:"Flips, Slides and Turns · Math Song"},
  {id:"y5-grid-coordinates",strand:"Geometry",title:"Grid Maps & Coordinates",focus:"A3 • B5 • create a map",summary:"Read and create grid maps and use coordinates to locate objects.",outcomes:["Read coordinates on a grid map","Locate objects using coordinates","Create a simple grid map"],videoId:"xR0Tq8Rkg6c",videoTitle:"Simple Grid Maps for Kids · Twinkl",videoId2:"q4MZC-9cU7s",videoTitle2:"Coordinates for Kids · Math with Mr. J"},
  {id:"y5-measurement-data",strand:"Statistics",title:"Measurement Data & Grouped Tables",focus:"Round • group • compare",summary:"Collect measurement data, round it consistently and organise it into grouped tables.",outcomes:["Collect and round measurements","Group measurement data into intervals","Answer frequency questions from a table"],videoId:"zF_dBk8EPDk",videoTitle:"Collect, Organise and Graph Data · Scratch Garden",videoId2:"x0Pn3mJUzZE",videoTitle2:"Making Tally Charts · Math for Kids"},
  {id:"y5-bivariate-data",strand:"Statistics",title:"Bivariate Data & Clustered Bar Graphs",focus:"Two categories • compare • explain",summary:"Collect paired categorical data, create clustered bar graphs and explain the comparisons they show.",outcomes:["Collect two types of information together","Read a clustered bar graph","Compare groups and explain patterns"],videoId:"yZJR2MzkBrU",videoTitle:"Bar Graphs & Picture Graphs · NUMBEROCK",videoId2:"twz45pt3Cp4",videoTitle2:"Compare Picture and Bar Graphs · Khan Academy",videoId3:"ChNSv1Agcbk",videoTitle3:"Draw Conclusions from Data · Math with Mr. J"},
  {id:"y5-chance",strand:"Probability",title:"Chance Experiments & Likelihood",focus:"Impossible to certain • 0 to 1",summary:"Run chance experiments, describe likelihood and place events on a probability number line from zero to one.",outcomes:["Identify outcomes in a chance experiment","Use impossible, unlikely, even chance, likely and certain","Place likelihood on a 0–1 number line"],videoId:"s_wKgmwXC74",videoTitle:"Probability for Kids · Math with Mr. J",videoId2:"Y-L4p9q4z-w",videoTitle2:"Likelihood and Chance · Numberock"},
];

const TOPICS_BY_YEAR:Record<YearLevel,Topic[]> = {2:TOPICS,3:YEAR3_TOPICS,4:YEAR4_TOPICS,5:YEAR5_TOPICS};
const OFFICIAL_PRACTICE_URLS:Partial<Record<YearLevel,string>> = {3:"https://nzc-maths-practice.nz/year/Year%203/",4:"https://nzc-maths-practice.nz/year/Year%204/",5:"https://nzc-maths-practice.nz/year/Year%205/"};

function hashText(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed:number){return()=>{seed+=0x6D2B79F5;let t=seed;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffled<T>(items:T[], random:()=>number){return [...items].sort(()=>random()-.5)}
function numericChoices(correct:number, random:()=>number, suffix=""){const values=new Set<number>([correct]);let guard=0;while(values.size<4&&guard++<30){const jump=1+Math.floor(random()*Math.max(3,Math.min(10,Math.abs(correct)||3)));values.add(Math.max(0,correct+(random()>.5?jump:-jump)))}return shuffled([...values].map(v=>`${v}${suffix}`),random)}
function q(prompt:string, answer:string, choices:string[], hint:string, random:()=>number):Question{return{prompt,answer,choices:shuffled([...new Set([answer,...choices])].slice(0,4),random),hint}}
function maoriNumber(n:number){const ones=["kore","tahi","rua","toru","whā","rima","ono","whitu","waru","iwa"];if(n<10)return ones[n];if(n===10)return"tekau";if(n===100)return"kotahi rau";const tens=Math.floor(n/10),one=n%10;const lead=tens===1?"tekau":`${ones[tens]} tekau`;return one?`${lead} mā ${ones[one]}`:lead}

function makeQuestions(topic:Topic,setIndex:number):Question[]{
  const random=rng(hashText(`${topic.id}-${setIndex}`));
  const pick=<T,>(xs:T[])=>xs[Math.floor(random()*xs.length)];
  const out:Question[]=[];
  const shapes=[{n:"triangle",f:"3 sides"},{n:"square",f:"4 equal sides"},{n:"pentagon",f:"5 sides"},{n:"hexagon",f:"6 sides"},{n:"cube",f:"6 square faces"},{n:"cuboid",f:"6 rectangular faces"},{n:"cone",f:"1 flat face and 1 curved surface"},{n:"pyramid",f:"triangular faces meeting at a vertex"}];
  const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
  for(let i=0;i<20;i++){
    if(topic.id==="numbers-120"){
      const n=2+Math.floor(random()*117); const mode=i%4;
      if(mode===0)out.push(q(`What number comes after ${n}?`,`${n+1}`,numericChoices(n+1,random),"Count forward one.",random));
      else if(mode===1)out.push(q(`What number comes before ${n}?`,`${n-1}`,numericChoices(n-1,random),"Count backward one.",random));
      else if(mode===2){const m=Math.min(120,n+1+Math.floor(random()*12));out.push(q(`Which number is greater: ${n} or ${m}?`,`${m}`,[`${n}`,`${Math.max(0,n-1)}`,`${Math.min(120,m+1)}`],"The greater number is farther along the counting sequence.",random))}
      else{const a=Math.floor(random()*100),b=Math.min(120,a+Math.floor(random()*18)+1);out.push(q(`Put these in order from smallest to largest: ${b}, ${a}, ${Math.floor((a+b)/2)}`,`${a}, ${Math.floor((a+b)/2)}, ${b}`,[`${b}, ${Math.floor((a+b)/2)}, ${a}`,`${a}, ${b}, ${Math.floor((a+b)/2)}`,`${Math.floor((a+b)/2)}, ${a}, ${b}`],"Start with the number closest to zero.",random))}
    } else if(topic.id==="skip-counting"){
      const step=pick([1,2,5,10]),start=Math.floor(random()*(121-step*3));const seq=[start,start+step,start+step*2,start+step*3];const missing=1+Math.floor(random()*2),answer=seq[missing];out.push(q(`Fill the gap: ${seq.map((v,j)=>j===missing?"__":v).join(", ")}`,`${answer}`,numericChoices(answer,random),`The pattern changes by ${step} each time.`,random));
    } else if(topic.id==="te-reo-numbers"){
      const n=1+Math.floor(random()*100);if(i%2===0)out.push(q(`Which te reo Māori number means ${n}?`,maoriNumber(n),[maoriNumber(Math.max(1,n-1)),maoriNumber(Math.min(100,n+1)),maoriNumber(Math.max(1,n-10))],"Listen for the tens and ones.",random));else{const ans=`${n}`;out.push(q(`What number is “${maoriNumber(n)}”?`,ans,numericChoices(n,random),"Tekau means ten; mā joins the ones.",random))}
    } else if(topic.id==="place-value"){
      const n=10+Math.floor(random()*111),h=Math.floor(n/100),t=Math.floor((n%100)/10),o=n%10;const answer=n>=100?`${h} hundred, ${t} tens, ${o} ones`:`${t} tens and ${o} ones`;out.push(q(`How is ${n} partitioned?`,answer,[`${Math.max(0,t-1)} tens and ${o+10} ones`,`${o} tens and ${t} ones`,`${t+1} tens and ${o} ones`],"Read each digit by its place.",random));
    } else if(topic.id==="number-line"){
      const n=Math.floor(random()*121);if(i%2===0)out.push(q(`Is ${n} odd or even?`,n%2?"odd":"even",[n%2?"even":"odd","both","neither"],"Even numbers can be shared into pairs with none left over.",random));else{const m=Math.floor(random()*121),answer=n>m?">":n<m?"<":"=";out.push(q(`Choose the sign: ${n} __ ${m}`,answer,["<",">","="].filter(x=>x!==answer),"Imagine both numbers on a number line.",random))}
    } else if(topic.id==="add-sub"){
      const add=i%2===0;if(add){const a=10+Math.floor(random()*70),b=1+Math.floor(random()*Math.min(40,120-a));const ans=a+b;out.push(q(`${a} + ${b} = ?`,`${ans}`,numericChoices(ans,random),`Split ${b} into tens and ones.`,random))}else{const a=20+Math.floor(random()*101),b=1+Math.floor(random()*Math.min(50,a));const ans=a-b;out.push(q(`${a} − ${b} = ?`,`${ans}`,numericChoices(ans,random),`Subtract the tens, then the ones.`,random))}
    } else if(topic.id==="facts-doubles"){
      if(i%2===0){const n=1+Math.floor(random()*10),ans=n*2;out.push(q(`Double ${n} is…`,`${ans}`,numericChoices(ans,random),`Add ${n} to itself.`,random))}else{const n=2*(1+Math.floor(random()*10)),ans=n/2;out.push(q(`Half of ${n} is…`,`${ans}`,numericChoices(ans,random),"Share the number into two equal groups.",random))}
    } else if(topic.id==="groups-sharing"){
      const size=pick([2,5,10]),groups=1+Math.floor(random()*8),total=size*groups;if(i%2===0)out.push(q(`${groups} equal groups of ${size} make…`,`${total}`,numericChoices(total,random),`Skip count by ${size}, ${groups} times.`,random));else out.push(q(`${total} objects are shared into ${groups} equal groups. How many in each group?`,`${size}`,numericChoices(size,random),"Each group must have the same amount.",random));
    } else if(topic.id==="fractions"){
      const den=pick([2,3,4]),unit=1+Math.floor(random()*5),total=den*unit,word=den===2?"half":den===3?"third":"quarter";out.push(q(`What is one ${word} of ${total}?`,`${unit}`,numericChoices(unit,random),`Share ${total} into ${den} equal groups.`,random));
    } else if(topic.id==="money"){
      const values=[10,20,50,100,200,500,1000,2000],a=pick(values),b=pick(values.filter(v=>v+a<=2000)),total=a+b;
      const fmt=(v:number)=>v<100?`${v}c`:`$${Number.isInteger(v/100)?v/100:(v/100).toFixed(2)}`;
      if(i%4===0)out.push(q(`${fmt(a)} + ${fmt(b)} = ?`,fmt(total),[fmt(Math.max(10,total-10)),fmt(Math.min(2000,total+10)),fmt(Math.max(10,total-a))],"Put both amounts into cents or dollars, then add.",random));
      else if(i%4===1){const cents=pick([100,200,300,500,1000,2000]);out.push(q(`${cents} cents is the same as…`,fmt(cents),[fmt(Math.max(10,cents-100)),fmt(Math.min(2000,cents+100)),`${cents} dollars`],"Every 100 cents makes 1 dollar.",random))}
      else if(i%4===2){if(a===b){i--;continue}const larger=Math.max(a,b),smaller=Math.min(a,b);out.push(q(`Which amount is greater: ${fmt(a)} or ${fmt(b)}?`,fmt(larger),[fmt(smaller),fmt(Math.min(2000,larger+10)),"They are equal"],"Compare both amounts using the same unit.",random))}
      else{const target=pick([50,100,200,500,1000,2000]);const combinations:Record<number,string>={50:"20c + 20c + 10c",100:"50c + 50c",200:"$1 + $1",500:"$2 + $2 + $1",1000:"$5 + $5",2000:"$10 + $10"};out.push(q(`Which group makes ${fmt(target)}?`,combinations[target],[`${fmt(target)} + 10c`,fmt(Math.max(10,target-10)),`${fmt(target)} + ${fmt(target)}`],"Add the value of every New Zealand coin or note in the group.",random))}
    } else if(topic.id==="equations"){
      const a=1+Math.floor(random()*15),b=1+Math.floor(random()*10),c=1+Math.floor(random()*15),ans=a+b-c;if(ans>=0&&ans<=20)out.push(q(`${a} + ${b} = ${c} + __`,`${ans}`,numericChoices(ans,random),"Both sides of the equals sign must have the same value.",random));else{i--;continue}
    } else if(topic.id==="patterns"){
      const sets=[["red","blue","green"],["circle","square","triangle"],["clap","stomp","jump"],["1","2","3"]],pat=pick(sets),offset=Math.floor(random()*3),seq=Array.from({length:6},(_,j)=>pat[(j+offset)%3]),ans=pat[(6+offset)%3];out.push(q(`What comes next? ${seq.join(", ")}, __`,ans,pat.filter(x=>x!==ans).concat(["stop"]),"Find the part that repeats.",random));
    } else if(topic.id==="length"){
      const a=3+Math.floor(random()*10),b=3+Math.floor(random()*10);if(a===b){i--;continue}out.push(q(`A pencil is ${a} paper clips long. A crayon is ${b} paper clips long. Which is longer?`,a>b?"the pencil":"the crayon",[a>b?"the crayon":"the pencil","they are equal","we cannot compare"],"Both objects were measured with the same unit.",random));
    } else if(topic.id==="mass-capacity"){
      const a=1+Math.floor(random()*10),b=1+Math.floor(random()*10);if(a===b){i--;continue}const capacity=i%2===0;out.push(q(capacity?`Bottle A holds ${a} cups. Bottle B holds ${b} cups. Which holds more?`:`Object A balances ${a} blocks. Object B balances ${b} blocks. Which is heavier?`,a>b?"A":"B",[a>b?"B":"A","They are equal","Not enough information"],"The greater count shows more capacity or mass when the units are equal.",random));
    } else if(topic.id==="turns"){
      const dirs=["north","east","south","west"],start=Math.floor(random()*4),quarters=pick([1,2,3,4]),clockwise=random()>.5,finish=(start+(clockwise?quarters:-quarters)+8)%4;const turn=quarters===1?"a quarter":quarters===2?"a half":quarters===3?"a three-quarter":"a full";out.push(q(`Face ${dirs[start]}. Make ${turn} turn ${clockwise?"clockwise":"anti-clockwise"}. Which way are you facing?`,dirs[finish],dirs.filter(d=>d!==dirs[finish]),"A quarter turn moves to the next direction; a half turn faces the opposite way.",random));
    } else if(topic.id==="calendar"){
      const m=Math.floor(random()*12),mode=i%3;
      if(mode===0)out.push(q(`Which month comes after ${months[m]}?`,months[(m+1)%12],months.filter(x=>x!==months[(m+1)%12]).slice(0,3),"Move one step forward through the months.",random));
      else if(mode===1){const season=pick([["summer","December"],["autumn","March"],["winter","June"],["spring","September"]]);out.push(q(`In Aotearoa New Zealand, which month begins ${season[0]}?`,season[1],months.filter(x=>x!==season[1]).sort(()=>random()-.5).slice(0,3),"New Zealand is in the Southern Hemisphere.",random))}
      else {const durationItems=[
        ["the time for a blink","seconds"],["the time to brush your teeth","minutes"],["a school day","hours"],["a weekend","days"],["a school term","weeks"],["a season","months"],["a learner's age","years"]
      ] as const;const item=pick(durationItems);out.push(q(`Which duration unit is most sensible for ${item[0]}?`,item[1],durationItems.map(x=>x[1]).filter(x=>x!==item[1]).sort(()=>random()-.5).slice(0,3),"Choose the unit that matches how long the activity or event lasts.",random))}
    } else if(topic.id==="clock"){
      const hour=1+Math.floor(random()*12),minute=pick([0,15,30,45]),next=hour===12?1:hour+1;const wording=minute===0?`${hour} o'clock`:minute===15?`quarter past ${hour}`:minute===30?`half past ${hour}`:`quarter to ${next}`;const answer=`${hour}:${String(minute).padStart(2,"0")}`;out.push(q(`Which digital time means “${wording}”?`,answer,[`${next}:${String(minute).padStart(2,"0")}`,`${hour}:${String((minute+15)%60).padStart(2,"0")}`,`${next}:${String((60-minute)%60).padStart(2,"0")}`],"Past uses the current hour; quarter to points to the next hour.",random));
    } else if(topic.id==="shapes"){
      const item=pick(shapes);out.push(q(`Which shape has ${item.f}?`,item.n,shapes.filter(s=>s.n!==item.n).sort(()=>random()-.5).slice(0,3).map(s=>s.n),"Use the shape's features, not only its appearance.",random));
    } else if(topic.id==="shape-moves"){
      const orientations=["▲","▶","▼","◀"],start=Math.floor(random()*4),turn=i%2===0?1:2;
      const a=orientations[start],b=orientations[(start+turn)%4],c=orientations[(start+turn*2)%4],answer=orientations[(start+turn*3)%4];
      const turnName=turn===1?"quarter turn":"half turn";
      out.push(q(`SHAPE_PATTERN:${JSON.stringify({items:[{shape:a,op:"slide"},{shape:a,op:turnName},{shape:b,op:"slide"},{shape:b,op:turnName},{shape:c,op:"slide"},{shape:c,op:turnName}]})}`,answer,orientations.filter(x=>x!==answer),"A slide changes the position but keeps the same orientation. A turn changes the direction the shape points.",random));
    } else if(topic.id==="position"){
      const dirs=["left","right","forward","backward"],first=pick(dirs),second=pick(dirs);out.push(q(`A learner moves ${first}, then ${second}. Which instruction did they follow first?`,first,dirs.filter(d=>d!==first),"Read movement instructions in order.",random));
    } else if(topic.id==="collect-data"){
      const total=1+Math.floor(random()*12);if(i%2===0)out.push(q(`A tally chart shows ${"||||/ ".repeat(Math.floor(total/5))}${"|".repeat(total%5)}. What is the total?`,`${total}`,numericChoices(total,random),"Count each crossed bundle as five, then add the extra marks.",random));else out.push(q("Which question would collect useful data about favourite fruit?","What is your favourite fruit?",["Do you like things?","How old is the fruit?","What day is today?"],"A statistical question should allow different answers that can be grouped.",random))
    } else if(topic.id==="interpret-data"){
      const cats=2+Math.floor(random()*8),dogs=1+Math.floor(random()*7),fish=1+Math.floor(random()*5),values={cats,dogs,fish},mode=i%3;
      if(mode===0){const answer=Object.entries(values).sort((a,b)=>b[1]-a[1])[0][0];const least=Object.entries(values).sort((a,b)=>a[1]-b[1])[0][0];out.push(q(`Survey results — cats: ${cats}, dogs: ${dogs}, fish: ${fish}. Which category is most common?`,answer,[least,...Object.keys(values).filter(x=>x!==answer&&x!==least)],"The most common category has the greatest count.",random))}
      else if(mode===1){const names=Object.keys(values) as (keyof typeof values)[],a=pick(names),b=pick(names.filter(x=>x!==a)),diff=Math.abs(values[a]-values[b]);out.push(q(`Cats: ${cats}, dogs: ${dogs}, fish: ${fish}. How many more ${values[a]>=values[b]?a:b} than ${values[a]>=values[b]?b:a}?`,`${diff}`,numericChoices(diff,random),"Subtract the smaller category count from the larger count.",random))}
      else {const total=cats+dogs+fish;out.push(q(`Survey results — cats: ${cats}, dogs: ${dogs}, fish: ${fish}. What is the total number of responses?`,`${total}`,numericChoices(total,random),"Add all category counts to find the total.",random))}
    } else {
      const cats=2+Math.floor(random()*8),dogs=1+Math.floor(random()*7),fish=1+Math.floor(random()*5),mode=i%3;if(mode===0){const vals={cats,dogs,fish},answer=Object.entries(vals).sort((a,b)=>b[1]-a[1])[0][0];out.push(q(`Survey results — cats: ${cats}, dogs: ${dogs}, fish: ${fish}. Which is most common?`,answer,["cats","dogs","fish"].filter(x=>x!==answer),"Compare the three counts and choose the greatest.",random))}else if(mode===1){const ans=Math.abs(cats-dogs);out.push(q(`Cats: ${cats}. Dogs: ${dogs}. How many more are in the larger group?`,`${ans}`,numericChoices(ans,random),"Subtract the smaller count from the larger count.",random))}else{const ans=cats+dogs+fish;out.push(q(`Cats: ${cats}, dogs: ${dogs}, fish: ${fish}. How many responses altogether?`,`${ans}`,numericChoices(ans,random),"Add every category to find the total.",random))}
    }
  }
  return out;
}

function makeYear3Questions(topic:Topic,setIndex:number):Question[]{
  const random=rng(hashText(`${topic.id}-${setIndex}`));
  const pick=<T,>(xs:T[])=>xs[Math.floor(random()*xs.length)];
  const out:Question[]=[];
  const fraction=(n:number,d:number)=>`${n}/${d}`;
  const polygons:Record<number,string>={3:"triangle",4:"quadrilateral",5:"pentagon",6:"hexagon",7:"heptagon",8:"octagon",9:"nonagon",10:"decagon"};
  for(let i=0;i<20;i++){
    if(topic.id==="y3-numbers-1000"){
      const n=100+Math.floor(random()*900),h=Math.floor(n/100),t=Math.floor((n%100)/10),o=n%10;
      if(i%3===0)out.push(q(`How is ${n} partitioned?`,`${h} hundreds, ${t} tens and ${o} ones`,[`${h} tens, ${t} hundreds and ${o} ones`,`${h} hundreds, ${o} tens and ${t} ones`,`${n} tens`],"Read each digit by its place.",random));
      else if(i%3===1){const m=100+Math.floor(random()*900);if(n===m){i--;continue}out.push(q(`Which number is greater: ${n} or ${m}?`,`${Math.max(n,m)}`,[`${Math.min(n,m)}`,`${Math.max(n,m)-1}`,`${Math.min(n,m)+1}`],"Compare the hundreds first, then tens, then ones.",random))}
      else out.push(q(`What number is 10 more than ${n}?`,`${Math.min(1000,n+10)}`,numericChoices(Math.min(1000,n+10),random),"Increase the tens place by one.",random));
    } else if(topic.id==="y3-facts"){
      const factor=pick([2,3,4,5,8,10]),other=1+Math.floor(random()*10),product=factor*other;
      if(i%2===0)out.push(q(`${factor} × ${other} = ?`,`${product}`,numericChoices(product,random),`Skip count by ${factor}, ${other} times.`,random));
      else out.push(q(`${product} ÷ ${factor} = ?`,`${other}`,numericChoices(other,random),`Use the related fact ${factor} × ${other} = ${product}.`,random));
    } else if(topic.id==="y3-groups"){
      const groups=pick([2,3,4,5,8,10]),size=2+Math.floor(random()*24),total=groups*size;
      if(i%2===0)out.push(q(`${groups} bags hold ${size} apples each. How many apples altogether?`,`${total}`,numericChoices(total,random),`Multiply ${groups} by ${size}.`,random));
      else out.push(q(`${total} counters are shared equally among ${groups} children. How many does each child get?`,`${size}`,numericChoices(size,random),"Equal sharing is division.",random));
    } else if(topic.id==="y3-add-sub"){
      if(i%3===2){const a=50+Math.floor(random()*400),b=10+Math.floor(random()*200),c=10+Math.floor(random()*Math.min(200,a+b)),ans=a+b-c;out.push(q(`A learner had ${a} points, earned ${b}, then spent ${c}. How many points remain?`,`${ans}`,numericChoices(ans,random),"Add first, then subtract.",random))}
      else if(i%2===0){const a=100+Math.floor(random()*700),b=1+Math.floor(random()*(1000-a)),ans=a+b;out.push(q(`${a} + ${b} = ?`,`${ans}`,numericChoices(ans,random),"Add hundreds, tens and ones.",random))}
      else{const a=200+Math.floor(random()*801),b=10+Math.floor(random()*(a-10)),ans=a-b;out.push(q(`${a} − ${b} = ?`,`${ans}`,numericChoices(ans,random),"Subtract by place value and check with addition.",random))}
    } else if(topic.id==="y3-rounding"){
      const n=10+Math.floor(random()*981),base=i%2===0?10:100,ans=Math.round(n/base)*base;out.push(q(`Round ${n} to the nearest ${base}.`,`${ans}`,numericChoices(ans,random),`Look at the digit to the right of the ${base===10?"tens":"hundreds"} place: 5 or more rounds up.`,random));
    } else if(topic.id==="y3-fraction-represent"){
      const d=pick([2,3,4,5,6,8,10,12]),n=1+Math.floor(random()*(d-1));out.push(q(`${n} of ${d} equal parts are selected. Which fraction is selected?`,fraction(n,d),[fraction(d,n),fraction(Math.max(1,n-1),d),fraction(Math.min(d,n+1),d)],"The numerator counts selected parts; the denominator counts all equal parts.",random));
    } else if(topic.id==="y3-fraction-compare"){
      const a=pick([2,3,4,5,6,8,10,12]),b=pick([2,3,4,5,6,8,10,12].filter(x=>x!==a)),answer=a<b?fraction(1,a):fraction(1,b);out.push(q(`Which unit fraction is greater: ${fraction(1,a)} or ${fraction(1,b)}?`,answer,[answer===fraction(1,a)?fraction(1,b):fraction(1,a),"They are equal",fraction(1,12)],"For unit fractions, fewer equal pieces means each piece is larger.",random));
    } else if(topic.id==="y3-fraction-add"){
      const d=pick([3,4,5,6,8,10,12]),a=1+Math.floor(random()*(d-1));if(i%2===0){const b=1+Math.floor(random()*(d-a)),ans=a+b;out.push(q(`${fraction(a,d)} + ${fraction(b,d)} = ?`,fraction(ans,d),[fraction(ans,d+1),fraction(Math.max(1,ans-1),d),fraction(Math.min(d,ans+1),d)],"Add the numerators and keep the same denominator.",random))}else{const b=1+Math.floor(random()*a),ans=a-b;out.push(q(`${fraction(a,d)} − ${fraction(b,d)} = ?`,fraction(ans,d),[fraction(Math.max(0,ans-1),d),fraction(Math.min(d,ans+1),d),fraction(ans,d+1)],"Subtract the numerators and keep the same denominator.",random))}
    } else if(topic.id==="y3-money"){
      const prices=[50,120,180,250,340,460,550,720,850,1250,1470],price=pick(prices),payments=[500,1000,2000],payment=pick(payments.filter(x=>x>=price)),fmt=(v:number)=>v<100?`${v} cents`:`$${Math.floor(v/100)} and ${v%100} cents`;
      if(i%2===0)out.push(q(`An item costs ${fmt(price)}. A learner pays ${fmt(payment)}. What change should they receive?`,fmt(payment-price),[fmt(Math.max(0,payment-price-50)),fmt(payment-price+50),fmt(price)],"Change equals the payment minus the price.",random));
      else{const second=pick([20,50,100,200,350]),total=price+second;out.push(q(`${fmt(price)} + ${fmt(second)} = ?`,fmt(total),[fmt(Math.max(0,total-50)),fmt(total+50),fmt(price)],"Add cents to cents and dollars to dollars.",random))}
    } else if(topic.id==="y3-equality"){
      const a=50+Math.floor(random()*250),b=10+Math.floor(random()*100),c=20+Math.floor(random()*180),ans=a+b-c;
      if(ans<0){i--;continue}out.push(q(`${a} + ${b} = ${c} + □. What is □?`,`${ans}`,numericChoices(ans,random),"Both sides of the equals sign must have the same value.",random));
    } else if(topic.id==="y3-repeat-pattern"){
      const patterns=[["red","blue","green"],["circle","square"],["clap","stomp","stomp"],["A","B","C","C"]],pat=pick(patterns),seq=Array.from({length:7},(_,j)=>pat[j%pat.length]),ans=pat[7%pat.length];out.push(q(`What comes next? ${seq.join(", ")}, __`,ans,[...new Set(pat.filter(x=>x!==ans)),"stop"],"Find the shortest unit that repeats.",random));
    } else if(topic.id==="y3-growing-pattern"){
      const start=1+Math.floor(random()*20),step=pick([2,3,4,5,8,10]),seq=Array.from({length:5},(_,j)=>start+j*step),ans=start+5*step;out.push(q(`Continue the growing pattern: ${seq.join(", ")}, __`,`${ans}`,numericChoices(ans,random),`The rule is add ${step}.`,random));
    } else if(topic.id==="y3-pattern-rules"){
      const start=1+Math.floor(random()*15),step=pick([2,3,4,5,8,10]),seq=Array.from({length:4},(_,j)=>start+j*step);out.push(q(`What is the rule for ${seq.join(", ")}?`,`add ${step}`,[`subtract ${step}`,`add ${step+1}`,"alternate two colours"],"Compare each term with the one before it.",random));
    } else if(topic.id==="y3-metric"){
      const items=[{thing:"the length of a pencil",unit:"cm"},{thing:"the length of a classroom",unit:"m"},{thing:"the mass of an apple",unit:"g"},{thing:"the mass of a child",unit:"kg"},{thing:"medicine in a spoon",unit:"ml"},{thing:"water in a large bottle",unit:"l"}],item=pick(items);out.push(q(`Which metric unit is best for measuring ${item.thing}?`,item.unit,shuffled(["cm","m","g","kg","ml","l"].filter(x=>x!==item.unit),random).slice(0,3),"Choose a unit that matches what is measured and its likely size.",random));
    } else if(topic.id==="y3-compare-measure"){
      const unit=pick(["cm","g","ml"]),a=10+Math.floor(random()*490),b=10+Math.floor(random()*490);if(a===b){i--;continue}out.push(q(`Object A measures ${a}${unit}. Object B measures ${b}${unit}. Which has the greater measurement?`,a>b?"Object A":"Object B",[a>b?"Object B":"Object A","They are equal","The units are different"],"The units match, so compare the numbers.",random));
    } else if(topic.id==="y3-perimeter"){
      const length=2+Math.floor(random()*18),width=2+Math.floor(random()*12),ans=2*(length+width);out.push(q(`A rectangle is ${length} cm long and ${width} cm wide. What is its perimeter?`,`${ans} cm`,numericChoices(ans,random," cm"),"Add all four sides: length + width + length + width.",random));
    } else if(topic.id==="y3-area"){
      const length=2+Math.floor(random()*10),width=2+Math.floor(random()*8),ans=length*width;out.push(q(`A rectangle covers ${length} rows of ${width} equal squares. What is its area?`,`${ans} square units`,numericChoices(ans,random," square units"),"Multiply rows by squares in each row.",random));
    } else if(topic.id==="y3-event-duration"){
      const events=[{event:"brushing your teeth",unit:"minutes"},{event:"a blink",unit:"seconds"},{event:"a school day",unit:"hours"},{event:"a holiday trip",unit:"days"},{event:"a school term",unit:"weeks"},{event:"growing from age 7 to age 8",unit:"year"}],item=pick(events);out.push(q(`Which unit best describes the duration of ${item.event}?`,item.unit,shuffled(["seconds","minutes","hours","days","weeks","year"].filter(x=>x!==item.unit),random).slice(0,3),"Choose a unit that gives a sensible-sized number.",random));
    } else if(topic.id==="y3-clock"){
      const hour=1+Math.floor(random()*12),minute=Math.floor(random()*12)*5,next=hour===12?1:hour+1,words=minute===0?`${hour} o'clock`:minute<=30?`${minute} minutes past ${hour}`:`${60-minute} minutes to ${next}`;out.push(q(`Which digital time matches “${words}”?`,`${hour}:${String(minute).padStart(2,"0")}`,[`${next}:${String(minute).padStart(2,"0")}`,`${hour}:${String((minute+5)%60).padStart(2,"0")}`,`${next}:${String(60-minute).padStart(2,"0")}`],"Past uses the current hour; to counts toward the next hour.",random));
    } else if(topic.id==="y3-time-units"){
      const facts=[{p:"How many seconds are in 1 minute?",a:60},{p:"How many minutes are in 1 hour?",a:60},{p:"How many hours are in 1 day?",a:24},{p:"How many days are in 1 week?",a:7},{p:"How many months are in 1 year?",a:12},{p:"How many years are in 1 decade?",a:10}],fact=pick(facts);out.push(q(fact.p,`${fact.a}`,numericChoices(fact.a,random),"Think about the relationship between the two time units.",random));
    } else if(topic.id==="y3-polygons"){
      const sides=3+Math.floor(random()*8);out.push(q(`Which regular polygon has ${sides} sides?`,polygons[sides],Object.values(polygons).filter(x=>x!==polygons[sides]).sort(()=>random()-.5).slice(0,3),"A polygon's name tells how many straight sides it has.",random));
    } else if(topic.id==="y3-sort-shapes"){
      const facts=[{p:"Which shape has 6 square faces?",a:"cube",c:["cuboid","cone","pyramid"]},{p:"Which shape has 3 sides and 3 corners?",a:"triangle",c:["square","pentagon","circle"]},{p:"Which shape has one flat face and one curved surface?",a:"cone",c:["cube","sphere","pyramid"]},{p:"Which shape has 8 vertices?",a:"cuboid",c:["cone","sphere","triangle"]}],fact=pick(facts);out.push(q(fact.p,fact.a,fact.c,"Sort shapes by their mathematical features.",random));
    } else if(topic.id==="y3-symmetry"){
      const facts=[{p:"What does a line of symmetry do?",a:"divides a shape into matching reflected halves",c:["measures its perimeter","counts its corners","turns it into a circle"]},{p:"Which shape always has 4 lines of symmetry?",a:"square",c:["scalene triangle","parallelogram","uneven pentagon"]},{p:"If a design matches when folded on a line, the design is…",a:"symmetrical",c:["irregular","three-dimensional","measured"]}],fact=pick(facts);out.push(q(fact.p,fact.a,fact.c,"Imagine folding along the line: both halves should match exactly.",random));
    } else if(topic.id==="y3-directions"){
      const dirs=["north","east","south","west"],start=Math.floor(random()*4),turn=pick([1,2,-1,-2]),finish=(start+turn+4)%4,words=Math.abs(turn)===1?"a quarter turn":"a half turn",way=turn>0?"clockwise":"anti-clockwise";out.push(q(`Face ${dirs[start]}. Turn ${words} ${way}. Which way are you facing?`,dirs[finish],dirs.filter(x=>x!==dirs[finish]),"A quarter turn moves one compass direction; a half turn faces the opposite way.",random));
    } else if(topic.id==="y3-maps"){
      const facts=[{p:"The library is north of the playground. Where is the playground from the library?",a:"south",c:["north","east","west"]},{p:"The pool is east of the school. Where is the school from the pool?",a:"west",c:["east","north","south"]},{p:"A map key says ★ means playground. What does ★ show?",a:"the playground",c:["north","the map scale","a road"]}],fact=pick(facts);out.push(q(fact.p,fact.a,fact.c,"Use the map relationship or key exactly as described.",random));
    } else if(topic.id==="y3-data-collect"){
      const facts=[{p:"Which is a useful statistical question?",a:"What are the shoe sizes in our class?",c:["Is 4 + 3 equal to 7?","What is my name?","Is this pencil blue?"]},{p:"Why do we organise survey answers into categories?",a:"to compare and count similar responses",c:["to change the answers","to remove every difference","to avoid collecting data"]}],fact=pick(facts);out.push(q(fact.p,fact.a,fact.c,"A statistical question expects varied answers that can be collected and compared.",random));
    } else if(topic.id==="y3-data-present"){
      const total=2+Math.floor(random()*24);if(i%2===0)out.push(q(`A tally shows ${"||||/ ".repeat(Math.floor(total/5))}${"|".repeat(total%5)}. What value should the graph show?`,`${total}`,numericChoices(total,random),"Each complete tally bundle represents five.",random));else out.push(q("Which graph uses separate rectangular bars to compare categories?","bar graph",["number line","clock face","shape pattern"],"The height or length of each bar represents a category's count.",random));
    } else {
      const cats=2+Math.floor(random()*14),dogs=2+Math.floor(random()*14),birds=1+Math.floor(random()*10);if(i%3===0){if(cats===dogs||cats===birds||dogs===birds){i--;continue}const values={cats,dogs,birds},answer=Object.entries(values).sort((a,b)=>b[1]-a[1])[0][0];out.push(q(`Pet survey — cats: ${cats}, dogs: ${dogs}, birds: ${birds}. Which category is most common?`,answer,["cats","dogs","birds"].filter(x=>x!==answer),"Choose the category with the greatest count.",random))}else if(i%3===1){const ans=cats+dogs+birds;out.push(q(`Cats: ${cats}, dogs: ${dogs}, birds: ${birds}. How many responses altogether?`,`${ans}`,numericChoices(ans,random),"Add all categories.",random))}else{const ans=Math.abs(cats-dogs);out.push(q(`Cats: ${cats}, dogs: ${dogs}. What is the difference between the categories?`,`${ans}`,numericChoices(ans,random),"Subtract the smaller count from the larger count.",random))}
    }
  }
  return out;
}

function makeYear45Questions(topic:Topic,setIndex:number):Question[]{
  const random=rng(hashText(topic.id+"-"+setIndex)); const pick=<T,>(xs:T[])=>xs[Math.floor(random()*xs.length)]; const out:Question[]=[];
  for(let i=0;i<20;i++){ const id=topic.id;
    if(/numbers|round|decimal/.test(id)){const n=id.includes("million")?100000+Math.floor(random()*800000):100+Math.floor(random()*9900);const base=id.includes("round")?pick([10,100,1000]):10;const ans=id.includes("round")?Math.round(n/base)*base:n+10;out.push(q(id.includes("round")?"Round "+n+" to the nearest "+base+".":"What is 10 more than "+n+"?",String(ans),numericChoices(ans,random),"Use place value.",random));}
    else if(/times|multiply|divide/.test(id)){const a=pick([3,4,5,6,8,9,11,12]),b=2+Math.floor(random()*12),product=a*b;if(i%2===0)out.push(q(a+" × "+b+" = ?",String(product),numericChoices(product,random),"Use a known multiplication fact.",random));else out.push(q(product+" ÷ "+a+" = ?",String(b),numericChoices(b,random),"Use the related multiplication fact.",random));}
    else if(/fraction/.test(id)){const d=pick([2,4,5,8,10]),a=1+Math.floor(random()*(d-1)),b=1+Math.floor(random()*(d-a));if(i%2===0)out.push(q(a+"/"+d+" + "+b+"/"+d+" = ?",(a+b)+"/"+d,[(a+b)+"/"+(d+1),(a+b-1)+"/"+d,a+"/"+(d+1)],"Add numerators and keep the denominator.",random));else out.push(q("Which fraction is equivalent to "+a+"/"+d+"?",a*2+"/"+d*2,[a+1+"/"+d,a+"/"+(d+1),d+"/"+a],"Equivalent fractions name the same amount.",random));}
    else if(id.includes("money")){const cost=100+50*Math.floor(random()*20),paid=cost+100+50*Math.floor(random()*10),change=paid-cost;out.push(q("Find the change in cents when you pay "+paid+" cents for an item costing "+cost+" cents.",String(change),numericChoices(change,random),"Change is payment minus cost.",random));}
    else if(id.includes("equation")||id.includes("pattern")){const start=2+Math.floor(random()*15),step=pick([2,3,4,5]),answer=start+step*3;out.push(q("Continue: "+start+", "+(start+step)+", "+(start+step*2)+", __",String(answer),numericChoices(answer,random),"Find the pattern rule.",random));}
    else if(/metric|tools|duration|timetable|angles|irregular/.test(id)){const facts=[{p:"Which unit is best for a bottle of water?",a:"litres",c:["centimetres","kilograms","degrees"]},{p:"How many minutes are in 2 hours?",a:"120",c:["20","60","200"]},{p:"Which angle is greater than 90° but less than 180°?",a:"obtuse",c:["acute","right","full"]}];const f=pick(facts);out.push(q(f.p,f.a,f.c,"Choose the unit or angle that fits.",random));}
    else if(/area|volume|perimeter/.test(id)){const l=2+Math.floor(random()*8),w=2+Math.floor(random()*8),answer=id.includes("perimeter")?2*(l+w):l*w;out.push(q(id.includes("perimeter")?"A rectangle is "+l+" cm by "+w+" cm. What is its perimeter?":"A rectangle is "+l+" units by "+w+" units. What is its area?",String(answer),numericChoices(answer,random),id.includes("perimeter")?"Add all four sides.":"Multiply rows by columns.",random));}
    else if(/polygon|symmetry|transform|prism|parallel|grid/.test(id)){const facts=[{p:"Which transformation slides a shape without turning it?",a:"translation",c:["rotation","reflection","measurement"]},{p:"What do perpendicular lines make?",a:"a right angle",c:["a curved line","a circle","a fraction"]},{p:"Which shape has matching halves across a line?",a:"a symmetrical shape",c:["a graph","a table","a random shape"]}];const f=pick(facts);out.push(q(f.p,f.a,f.c,"Use the feature named in the question.",random));}
    else {const a=2+Math.floor(random()*12),b=2+Math.floor(random()*12),answer=a>b?"Category A":"Category B";out.push(q("Category A has "+a+" results and Category B has "+b+". Which is more common?",answer,[answer==="Category A"?"Category B":"Category A","They are equal","Neither category"],"Compare the two counts.",random));}
  } return out;
}

export default function MathsApp(){
  const [year,setYear]=useState<YearLevel>(2);
  const [topicId,setTopicId]=useState(TOPICS[0].id);
  const [strand,setStrand]=useState<Strand>("Number");
  const [progress,setProgress]=useState<Progress>({});
  const [quiz,setQuiz]=useState<{set:number;index:number;answers:string[]}|null>(null);
  const [selected,setSelected]=useState<string|null>(null);
  const activeTopics=TOPICS_BY_YEAR[year];
  const topic=activeTopics.find(t=>t.id===topicId)||activeTopics[0];
  const questions=useMemo(()=>quiz?(year===2?makeQuestions(topic,quiz.set):year===3?makeYear3Questions(topic,quiz.set):makeYear45Questions(topic,quiz.set)):[],[topic,quiz?.set,year]);
  useEffect(()=>{try{const saved=localStorage.getItem(PROGRESS_KEY)||localStorage.getItem(LEGACY_PROGRESS_KEY);if(saved){setProgress(JSON.parse(saved));if(!localStorage.getItem(PROGRESS_KEY))localStorage.setItem(PROGRESS_KEY,saved)}}catch{}},[]);
  const completed=activeTopics.reduce((sum,t)=>sum+Object.keys(progress).filter(k=>k.startsWith(`${t.id}-`)).length,0),totalSets=activeTopics.length*10;
  const selectTopic=(next:Topic)=>{setTopicId(next.id);setStrand(next.strand);setQuiz(null);setSelected(null);window.scrollTo({top:0,behavior:"smooth"})};
  const selectYear=(nextYear:YearLevel)=>{const nextTopics=TOPICS_BY_YEAR[nextYear];setYear(nextYear);setStrand("Number");setTopicId(nextTopics[0].id);setQuiz(null);setSelected(null);window.scrollTo({top:0,behavior:"smooth"})};
  const startSet=(set:number)=>{setQuiz({set,index:0,answers:[]});setSelected(null);window.scrollTo({top:0,behavior:"smooth"})};
  const choose=(answer:string)=>{if(!quiz||selected)return;setSelected(answer)};
  const next=()=>{if(!quiz||!selected)return;const answers=[...quiz.answers,selected];if(quiz.index===19){const score=answers.reduce((sum,a,j)=>sum+(a===questions[j].answer?1:0),0);const nextProgress={...progress,[`${topic.id}-${quiz.set}`]:{score,completedAt:new Date().toISOString()}};setProgress(nextProgress);localStorage.setItem(PROGRESS_KEY,JSON.stringify(nextProgress));setQuiz({...quiz,index:20,answers});setSelected(null)}else{setQuiz({...quiz,index:quiz.index+1,answers});setSelected(null)}};
  const current=quiz&&quiz.index<20?questions[quiz.index]:null;
  const finalScore=quiz&&quiz.index===20?quiz.answers.reduce((sum,a,j)=>sum+(a===questions[j].answer?1:0),0):0;
  const openVideo=topic.videoUrl||`https://www.youtube.com/watch?v=${topic.videoId}${topic.videoStart?`&t=${topic.videoStart}s`:""}`;

  if(quiz){
    const shapeData=current?.prompt.startsWith("SHAPE_PATTERN:")?JSON.parse(current.prompt.slice(14)) as {items:{shape:string;op:string}[]}:null;
    return <main className="quiz-page"><header className="quiz-top"><button className="back" onClick={()=>{setQuiz(null);setSelected(null)}}>← Back to {topic.title}</button><div className="quiz-meta"><span>Set {quiz.set}</span><b>{Math.min(quiz.index+1,20)} / 20</b></div></header>{current?<section className="quiz-card"><div className="quiz-progress"><span style={{width:`${(quiz.index/20)*100}%`}} /></div><p className="question-label">QUESTION {quiz.index+1}</p>{shapeData?<><h1 className="shape-question-title">What shape orientation comes next?</h1><div className="shape-sequence">{shapeData.items.map((item,index)=><div className="shape-step" key={`${index}-${item.shape}`}><div className="shape-tile">{item.shape}</div><span>{item.op}</span></div>)}<div className="shape-step"><div className="shape-tile missing">?</div></div></div></>:<h1>{current.prompt}</h1>}<div className="answers">{current.choices.map(choice=><button key={choice} onClick={()=>choose(choice)} className={`answer-choice ${shapeData?"shape-choice":""} ${selected?choice===current.answer?"correct":choice===selected?"wrong":"dim":""}`}>{shapeData?<span className="answer-shape">{choice}</span>:choice}</button>)}</div>{selected&&<div className={selected===current.answer?"feedback good":"feedback try"}><b>{selected===current.answer?"Ka pai! Correct.":"Not quite — keep learning."}</b><p>{current.hint}</p><button onClick={next}>{quiz.index===19?"See my result":"Next question →"}</button></div>}</section>:<section className="result-card"><div className="result-ring">{finalScore}<small>/20</small></div><p className="eyebrow">SET {quiz.set} COMPLETE</p><h1>{finalScore>=16?"Excellent exploring!":finalScore>=12?"Good progress!":"Let’s practise this trail again."}</h1><p>Your result is saved on this device. Try another set, or repeat this one to improve.</p><div className="result-actions"><button onClick={()=>startSet(quiz.set)}>Try set again</button><button className="primary" onClick={()=>{setQuiz(null);setSelected(null)}}>Choose another set</button></div></section>}</main>
  }

  return <main className="app-shell">
    <header className="site-header"><a className="identity" href="#top"><span className="mark" aria-hidden="true">NZ</span><span><b>NZ Maths Curriculum</b><small>New Zealand Years 2–5</small></span></a><div className="overall"><span><b>{completed}</b> of {totalSets} Year {year} sets complete</span><div><i style={{width:`${completed/totalSets*100}%`}} /></div></div><a className="curriculum-link" href={CURRICULUM_URLS[year]} target="_blank" rel="noreferrer">Year {year} Curriculum ↗</a></header>
    <nav className="year-tabs" aria-label="Choose school year"><span>Choose a learning level</span><div>{([2,3,4,5] as YearLevel[]).map(level=><button key={level} className={year===level?"active":""} onClick={()=>selectYear(level)}><b>Year {level}</b><small>{`87397 knowledge points`}</small></button>)}</div></nav>
    <div className="strand-bar" aria-label="Curriculum strands">{STRANDS.map(s=><button key={s} className={strand===s?"active":""} onClick={()=>{setStrand(s);const first=activeTopics.find(t=>t.strand===s)!;selectTopic(first)}}><span>{s==="Number"?"123":s==="Algebra"?"=":s==="Measurement"?"↔":s==="Geometry"?"◇":"▥"}</span>{s}</button>)}</div>
    <div className="workspace" id="top"><aside className="topic-list"><p className="list-label">Year {year} · {strand} trail</p>{activeTopics.filter(t=>t.strand===strand).map((t,index)=><button key={t.id} className={t.id===topic.id?"selected":""} onClick={()=>selectTopic(t)}><span className="topic-number">{String(index+1).padStart(2,"0")}</span><span><b>{t.title}</b><small>{t.focus}</small></span><i>{Object.keys(progress).filter(k=>k.startsWith(`${t.id}-`)).length}/10</i></button>)}</aside>
      <section className="lesson"><div className="trail"><span>Year {year} · {topic.strand}</span><b>Knowledge point {activeTopics.indexOf(topic)+1} of {activeTopics.length}</b></div><h1>{topic.title}</h1><p className="topic-focus">{topic.focus}</p><p className="summary">{topic.summary}</p>
        {topic.id.includes("money")&&<section className={`money-guide ${topic.id.includes("money")?"real-nz-money":""}`} aria-label="New Zealand money guide"><div><p className="eyebrow">THE BIG IDEA</p><h2>Money tells us how much something is worth.</h2><p>New Zealand uses dollars and cents. One dollar has the same value as 100 cents.{year===3?" Change is the payment minus the price.":""}</p><div className="money-equation"><b>$1</b><span>=</span><b>100c</b></div></div><div><p className="eyebrow">NEW ZEALAND MONEY</p>{topic.id.includes("money")?<><div className="nz-coin-gallery" aria-label="Real New Zealand coins">{NZ_COINS.map(coin=><figure key={coin.value}><img src={coin.src} alt={coin.alt}/><figcaption>{coin.value}</figcaption></figure>)}</div><div className="nz-note-values" aria-label="New Zealand note values used up to twenty dollars"><span>$5 note</span><span>$10 note</span><span>$20 note</span></div><p className="currency-credit">Coin images: Reserve Bank of New Zealand — Te Pūtea Matua. One-sided, low-resolution reproductions for education.</p><a className="currency-source" href="https://www.rbnz.govt.nz/money-and-cash/banknotes-and-coins/coins-in-circulation/coin-specifications-and-images-by-denomination" target="_blank" rel="noreferrer">Explore official NZ coins ↗</a><p className="money-note"><b>Video note:</b> The ASB GetWise video introduces what money is. Use the official coin images and note values here for New Zealand money.</p></>:<><div className="denominations"><span>10c</span><span>20c</span><span>50c</span><span>$1</span><span>$2</span><span>$5</span><span>$10</span><span>$20</span></div><p className="money-note"><b>Video note:</b> Use the New Zealand dollar and cent values shown here; the practice below uses New Zealand money.</p></>}</div></section>}
        {topic.id==="y4-nz-money"&&<section className="money-rounding" aria-label="Round money to the nearest dollar"><div><p className="eyebrow">ROUND MONEY TO THE NEAREST DOLLAR</p><h2>Look at the cents.</h2><p><b>0–49 cents:</b> round down. <b>50–99 cents:</b> round up.</p></div><div className="money-rounding-examples"><span><b>$12.30</b><i>→</i><strong>$12</strong><small>30c rounds down</small></span><span><b>$12.50</b><i>→</i><strong>$13</strong><small>50c rounds up</small></span><span><b>$19.99</b><i>→</i><strong>$20</strong><small>99c rounds up</small></span></div></section>}
        <div className="lesson-grid"><div className="video-column">{topic.id==="y4-times-facts"?<div className="video-card times-table-card"><div className="times-table-head"><small>TIMES TABLE REFERENCE</small><h2>1–10 multiplication table</h2><p>Read across each row. Cover an answer, say it aloud, then check.</p></div><div className="times-table-grid" aria-label="Multiplication table from one to ten">{Array.from({length:10},(_,row)=><div className="times-row" key={row}>{Array.from({length:row+1},(_,column)=>{const factor=column+1,multiplier=row+1;return <span key={multiplier}><b>{factor} × {multiplier} = {factor*multiplier}</b></span>})}</div>)}</div></div>:<div className="video-card"><div className="video-frame"><iframe key={topic.id} src={`https://www.youtube-nocookie.com/embed/${topic.videoId}?rel=0`} title={topic.videoTitle} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="video-foot"><span><small>WATCH FIRST</small><b>{topic.videoTitle}</b></span><a href={openVideo} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div></div>}{topic.videoId2&&<div className="video-card"><div className="video-frame"><iframe key={`${topic.id}-second`} src={`https://www.youtube-nocookie.com/embed/${topic.videoId2}?rel=0`} title={topic.videoTitle2||"Related maths lesson"} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="video-foot"><span><small>WATCH NEXT</small><b>{topic.videoTitle2}</b></span><a href={`https://www.youtube.com/watch?v=${topic.videoId2}`} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div></div>}{topic.videoId3&&<div className="video-card"><div className="video-frame"><iframe key={`${topic.id}-third`} src={`https://www.youtube-nocookie.com/embed/${topic.videoId3}?rel=0`} title={topic.videoTitle3||"Related maths lesson"} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="video-foot"><span><small>WATCH NEXT</small><b>{topic.videoTitle3}</b></span><a href={`https://www.youtube.com/watch?v=${topic.videoId3}`} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div></div>}{topic.videoId4&&<div className="video-card"><div className="video-frame"><iframe key={`${topic.id}-fourth`} src={`https://www.youtube-nocookie.com/embed/${topic.videoId4}?rel=0`} title={topic.videoTitle4||"Related maths lesson"} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="video-foot"><span><small>WATCH NEXT</small><b>{topic.videoTitle4}</b></span><a href={`https://www.youtube.com/watch?v=${topic.videoId4}`} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div></div>}</div>
          <div className="goals-card"><p className="eyebrow">YOU WILL LEARN TO</p><ul>{topic.outcomes.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></div></div>
        <section className="practice-section"><div className="practice-heading"><div><p className="eyebrow">ONLINE PRACTICE</p><h2>10 sets · 20 questions each</h2><p>Choose any set. Questions change across the trail and give instant feedback.</p></div><span className="saved-note">Progress saves on this device</span></div>{OFFICIAL_PRACTICE_URLS[year]&&<a className="official-practice" href={OFFICIAL_PRACTICE_URLS[year]} target="_blank" rel="noreferrer"><span className="official-mark">NZ</span><span><small>NZ CURRICULUM PRACTICE</small><b>Try the official Year {year} maths activities</b><p>More online practice linked by the New Zealand Ministry of Education.</p></span><strong>Open Year {year} practice ↗</strong></a>}<div className="set-grid">{Array.from({length:10},(_,i)=>i+1).map(set=>{const result=progress[`${topic.id}-${set}`];return <button key={set} onClick={()=>startSet(set)} className={result?"done":""}><span>{result?"✓":set}</span><b>Set {set}</b><small>{result?`${result.score}/20 · Try again`:"20 questions"}</small></button>})}</div></section>
      </section></div>
    <footer><p>Built around the Ministry of Education’s Years 2–5 Mathematics and Statistics expectations.</p><a href={CURRICULUM_URLS[year]} target="_blank" rel="noreferrer">View the official Year {year} guide ↗</a></footer>
  </main>
}
